### ISSUE TITLE
Recurring events

### ISSUE THREAD

**Issue by mzur** [mzur/kirby-calendar-plugin#15]
Explore how recurring events could be implemented.

Ideas:
- Calendar `getEvents()` and `getAllEvents()` get optional arguments to specify a termination date in the future. All recurring events only return the single events until this date (else there may be infinite events).
- Events are extended to be recurring events. Maybe make a new class? Events get a new method `expand()` or some such that returns the list of single events until the termination date.
- When `getEvents()` or `getAllEvents()` is called, the list of events is created by a call to `expand()` of all (future) events of the calendar. This list is then sorted and returned.

**Comment by lekkerduidelijk** [comment]
Thanks for your _great_ work on this plugin so far. It's been really useful!

I was wondering if you plan to work on the recurring events extension in the near future?
I'm trying to 'hack' weekly events into the events array by inserting them inside a foreach loop. It's do-able, but official support is always beter ofcourse :smile:

**Comment by mzur** [comment]
Hey, thanks, I'm glad you find it useful. I'm pretty busy right now so I'm afraid I won't find the time to implement this in the near future, sorry. But as always I'm open for pull requests :-)

**Comment by abeyang** [comment]
:+1: for recurring events!

**Comment by mzur** [comment]
This plugin won't be developed any further.
