### ISSUE TITLE
Demo?

### ISSUE THREAD

**Issue by janstieler** [mzur/kirby-calendar-plugin#20]
Hi,
exist a demo of the calendar plugin?

Kind regards,
jan

**Comment by chbach** [comment]
Hi Jan,
I used it here: <https://kickerliga-paderborn.de/termine> and you can also find a demo of the teaser snippet on the home page. However, the plugin by itself is very flexible so you can easily change the appearance and behaviour to your needs.

**Comment by janstieler** [comment]
Hi,
thanks for your reply.
What is the URL of the homepage?

**Comment by chbach** [comment]
Sorry, I meant the home page of *that* website. https://kickerliga-paderborn.de – The plugin does not have a homepage.
