### ISSUE TITLE
‘Too many keys’ error since Kirby v2.2.2 release

### ISSUE THREAD

**Issue by jolantis** [mzur/kirby-calendar-plugin#21]
Thanks for your great plugin, I've been using it for a while, but unfortunately since I updated from Kirby v2.1.2 to v2.2.2 I get the following error message:

```
Fatal error: Uncaught exception 'Exception' with message 'Too many keys: Opening at 2015-02-27. Open: Fri-Sa-Su 14.00-17.00' in
/path/to/site/kirby/toolkit/vendors/yaml/yaml.php:1057 Stack trace: #0
/path/to/site/kirby/toolkit/vendors/yaml/yaml.php(1096): Spyc->checkKeysInValue('Opening at 2015...') #1
/path/to/site/kirby/toolkit/vendors/yaml/yaml.php(588): Spyc->returnKeyValuePair('opening: Openin...') #2
/path/to/site/kirby/toolkit/vendors/yaml/yaml.php(525): Spyc->_parseLine('opening: Openin...') #3
/path/to/site/kirby/toolkit/vendors/yaml/yaml.php(474): Spyc->loadWithSource(Array) #4
/path/to/site/kirby/toolkit/vendors/yaml/yaml.php(152): Spyc->__load('-\n\n\t_begin_date...') #5
/path/to/site/kirby/toolkit/lib/yaml. in /path/to/site/kirby/toolkit/vendors/yaml/yaml.php on line 1057
```

Apparently something changed in Kirby v2.2.2, that the calendar plugin doesn't like… any help is welcome…

**Comment by mzur** [comment]
The YAML parser was probably updated and doesn't like the event definition any more. How does your events look like (especially the part with `Opening at 2015-02-27. Open: Fri-Sa-Su 14.00-17.00` etc.)?

**Comment by jolantis** [comment]
The part you are referring to looked like this:

```
opening: Opening at 2015-02-27. Open: Fri-Sa-Su 14.00-17.00
```

After removing the colon halfway the sentence directly after `Open` the error is gone. Meaning a colon in an event definition throws an error after the YAML parser update… but removing the colon solves my issue. Thanks.

**Comment by mzur** [comment]
Yes, you have to escape the colon. There are three ways you can do this:

Use quotes
 ```yaml
opening: "Opening at 2015-02-27. Open: Fri-Sa-Su 14.00-17.00"
```

Use `>` (for multiline text)
```yaml
opening: >
    Opening at 2015-02-27. Open: Fri-Sa-Su 14.00-17.00
```

Use `|` (for multiline text with preserved newlines)
```yaml
opening: |
    Opening at 2015-02-27. Open: Fri-Sa-Su 14.00-17.00
```
