### ISSUE TITLE
Where to place snippets and files

### ISSUE THREAD

**Issue by martinlex** [mzur/kirby-calendar-plugin#22]
This Kirby calendar seems very interesting.
I have tried to follow the guide, but the calendar does not return date and time. 
Only title and description will echo out.
Apart from that, it works great so far.

This is templates/calendar.php:

```
    <?php $calendar = calendar($page->calendar()->yaml()); ?>

    <?php
        snippet('calendar-table', array(
            'calendar' => $calendar,
            'fields'   => array(
                'summary'       => l::get('title'),
                'description'   => l::get('description'),
                '_begin_date'   => l::get('_begin_date'),
                '_begin_time'   => l::get('_begin_time'),
                '_end_date'     => l::get('_end_date'),
                '_end_time'     => l::get('_end_time')
            )
        ));
    ?>

```

Can you help me?

**Comment by mzur** [comment]
Since there already is some output, you seem to have installed the plugin correctly. You should not have to explicitly add e.g. `_begin_time` to the fields array since the date is a field by default (see `calendar-table`):
```php
<th><?php echo l::get('date') ?></th>
<?php foreach ($fields as $field): ?>
    <th><?php echo $field ?></th>
<?php endforeach ?>
```
How does the `calendar` structure field of the page content file look like?
