### ISSUE TITLE
end date if no time is given

### ISSUE THREAD

**Issue by bnomei** [mzur/kirby-calendar-plugin#23]
https://github.com/mzur/kirby-calendar-plugin/blob/master/calendar/lib/Event.php#L104

are you sure 'tomorrow' works as intended?

i had to patch it with this
```
//$this->endTimestamp = strtotime('tomorrow', $this->endTimestamp);
$e = $this->endTimestamp;
$this->endTimestamp = mktime(23,59,59, intval(date('n',$e)), intval(date('j',$e)), intval(date('Y',$e)));
```

**Comment by mzur** [comment]
For me it works like this:
```
php > $time = time();
php > var_dump(strftime('%x %X', $time));
php shell code:1:
string(17) "06/29/16 18:54:06"

php > $tomorrow = strtotime('tomorrow', $time);
php > var_dump(strftime('%x %X', $tomorrow));
php shell code:1:
string(17) "06/30/16 00:00:00"
```
If an event has no end time specified it should last the "whole day". I took the specification for a whole day event from [this page](https://www.innerjoin.org/iCalendar/all-day-events.html) which in turn describes [RFC2445](http://www.ietf.org/rfc/rfc2445.txt) with the iCal specification:

> Applying the logic of an event to a date, an 'all day' event is flagged as starting at the beginning of one day and lasting until the beginning of the next:
> 
>     DTSTART;VALUE=DATE:20020923
>     DTEND;VALUE=DATE:20020924 
> 
> gives an event lasting the whole day. Or to be very precise:
> 
>     DTSTART:20020923T000000
>     DTEND:20020924T000000

While this should be correct for whole day events it might cause confusing results if an event has a begin date, time and an end date _but no end time_ specified. Did this cause you problems?

**Comment by bnomei** [comment]
i see, so it was me not knowing the whole day definition, causing my problem. thank you for the explanation.
i have dates for begin and end but no times at all.
