### ISSUE TITLE
Allways Displaying no events

### ISSUE THREAD

**Issue by BlackStonedLover** [mzur/kirby-calendar-plugin#30]
I setuped like explained in the manual. 
It still shows up there are no Events Setuped.

![image](https://user-images.githubusercontent.com/10251323/45030181-516e0280-b04b-11e8-8d7d-54d3ceb7ab41.png)
I use the Calendar Table snippet

![image](https://user-images.githubusercontent.com/10251323/45030345-cd684a80-b04b-11e8-8b80-ce72413fdfae.png)

**Comment by BlackStonedLover** [comment]
`Title: Calendar

----

Calendar: 

- 
  summary: jhkhg
  description: jkghlghjkghl
  _begin_date: 2018-09-12
  _begin_time: 04:00
  _end_date: 2018-09-19
  _end_time: 02:00
- 
  summary: gfhgsdf
  description: hhsdfgt
  _begin_date: 2018-09-20
  _begin_time: 03:30
  _end_date: 2018-09-19
  _end_time: 03:30`


`<?php snippet('calendar-table') ?>`

To Display it

**Comment by mzur** [comment]
Please have a look at the [calendar snippet](https://github.com/mzur/kirby-calendar-plugin#calendar-snippet) section of the readme. You have to supply the calendar data and field names via the `calendar` and `fields` entries.

**Comment by konstantinkuehn** [comment]
Sorry for the late Response. 
Added this to  the sidebar:

`								<?php $calendar = calendar($page->calendar()->yaml()); ?>
						<?php
							   snippet('calendar-table', array(
								  'calendar' => $calendar,
								  'fields' => array(
									 'summary' => l::get('title'),
									 'description' => l::get('description')
								  )
							   ));
							 ?>`

Still same issue no events are displayed

**Comment by BlackStonedLover** [comment]
Sorry for the late Response.
Added this to the sidebar:
`
<?php $calendar = calendar($page->calendar()->yaml()); ?> <?php snippet('calendar-table', array( 'calendar' => $calendar, 'fields' => array( 'summary' => l::get('title'), 'description' => l::get('description') ) )); ?>`

Still same issue no events are displayed

**Comment by mzur** [comment]
Do you have the `title` and `description` variables defined in your translation files? Can you do a `var_dump($calendar)` and show the output?
