### ISSUE TITLE
How can I set this up in the panel?

### ISSUE THREAD

**Issue by rlb222** [mzur/kirby-calendar-plugin#33]
I'm having trouble installing this plugin. I'm not very experienced with Kirby, so maybe I missed things that are obvious for experienced Kirby devs.
I hope you can help.

1. 
In what directory should it be installed? I think its site/plugins/mzur/kirby-calendar is that correct? When downloading the source (MacOS) i get 'kirby-calendar-plugin-master' but in index.php it says 'mzur/kirby-calendar'

2.
Under **Panel**, the instruction state: "Take a look at the blueprints directory of this repo to see a full example."
I could not find a blueprints directory in this repo or any examples.
I have tried several things with a structure but I couldn't get it to work. Where should i look for an example of this calendar in a blueprint for the Panel?

3.
It would be nice to have a panel screenshot here. I had the idea of trying to add one if I had installed this, but installing is a problem for me.

Hope you can help, thanks, 
René

**Comment by rlb222** [comment]
Thanks for your message,
Yes good idea, I will. 

René 

—/—

**Comment by mzur** [comment]
1. The plugin should be installed in `site/plugins/` so the full path would be `site/plugins/kirby-calendar-plugin-master`.

2. Thanks for noting this. The readme was not updated properly. I've now added an [example blueprint](https://github.com/mzur/kirby-calendar-plugin#panel).

3. Thanks for suggesting this but I think a screenshot is not necssary.

**Comment by rlb222** [comment]
Thank you for getting back to me and giving me the information!
I will try installing it and see if it is a solution for my situation.
Thanks!

About 3.
The screenshot of the panel would give me an idea what the plugin does and what it looks like. So I could determine if its for me. Without installing it.
So that is why I think it would be helpful.
No problem If you think otherwise, I could be wrong about this. I am new to Kirby.  

Regards,
René

---//---
